<a href="https://colab.research.google.com/github/pararover/PHY02MJMN01R04_Lab-Manuals/blob/main/Experiment_05_Matrix_Transpose_Inverse.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Experiment 5

## Transpose of a matrix

### Objectives

1. To define a $3\times 3$ matrix $M$ with random integers between 0 and 2 as elements.
1. To find the transpose of $M$.
1. To verify that the product of $M$ and its transpose is a symmetric matrix.

### Importing required libraries

In [ ]:
import numpy as np

### Defining the matrix

In [ ]:
M = np.random.randint(0, 3, size=(3, 3))
print("Original Matrix M:")
print(M)

Original Matrix M:
[[2 0 2]
 [0 2 1]
 [0 1 1]]


### Finding transpose of the matrix

In [ ]:
M_T = M.T
print("\nTranspose of M (M_T):")
print(M_T)


Transpose of M (M_T):
[[2 0 0]
 [0 2 1]
 [2 1 1]]


### Computing product of matrix and its transpose

In [ ]:
P = np.dot(M, M_T)
print("\nProduct P = M * M_T:")
print(P)


Product P = M * M_T:
[[8 2 2]
 [2 5 3]
 [2 3 2]]


### Verification of symmetry of product matrix

In [ ]:
P_T = P.T
print("\nTranspose of P (P_T):")
print(P_T)

is_symmetric = np.array_equal(P, P_T)
print(f"\nIs the product matrix P symmetric? {is_symmetric}")

if is_symmetric:
    print("Verification successful: The product of M and its transpose is a symmetric matrix.")
else:
    print("Verification failed: The product of M and its transpose is NOT a symmetric matrix.")


Transpose of P (P_T):
[[8 2 2]
 [2 5 3]
 [2 3 2]]

Is the product matrix P symmetric? True
Verification successful: The product of M and its transpose is a symmetric matrix.
