<a href="https://colab.research.google.com/github/pararover/PHY02MJMN01R04_Lab-Manuals/blob/main/Unit_03_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numerical computations using the `NumPy` library

* `NumPy` is the core Python library for numerical computing.
* `NumPy` supports operations on compound data types like arrays and matrices.
* The first thing to learn is how to create arrays and matrices using the `NumPy` library.

## Importing the `NumPy` library

In [ ]:
import numpy as np

## Creating `NumPy` arrays

### Creating N-dimensional `NumPy` array from sequence `a`
```markdown
np.array(a)
```

In [ ]:
a = np.array([1, 5, 2, 7, 4])

print(a)

[1 5 2 7 4]


### Creating an evenly spaced 1D array from `start` to `stop`, excluding the `stop` value
```markdown
np.arange(start, stop, step)
```

In [ ]:
b = np.arange(5, 10, 0.5)

print(b)

[5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


### Creating a 1D array with length equal to `N`, including the `start` and `stop` values
```markdown
np.linspace(start, stop, N)
```

In [ ]:
c = np.linspace(-1, 1, 11)

print(c)

[-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1. ]


### Creating array of given shape and type, filled with 0's
```markdown
np.zeros(shape)
```

In [ ]:
d = np.zeros(5)

print(d)

[0. 0. 0. 0. 0.]


In [ ]:
e = np.zeros((3, 4))

print(e)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Creating array of given shape and type, filled with 1's
```markdown
np.ones(shape)
```

In [ ]:
f = np.ones(5)

print(f)

[1. 1. 1. 1. 1.]


In [ ]:
g = np.ones((3, 4))

print(g)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Array attributes

### Data type of an array
```markdown
A.dtype
```

In [ ]:
g.dtype

dtype('float64')

### Number of dimensions in an array
```markdown
A.ndim
```

In [ ]:
g.ndim

2

### Total number of elements in an array
```markdown
A.size
```

In [ ]:
g.size

12

### Rows and columns of an array
```markdown
A.shape
```

In [ ]:
g.shape

(3, 4)

## Functions of `NumPy` arrays

### Array functions

In [ ]:
b

`np.sum()`   `np.prod()`

In [ ]:
b.sum()

np.float64(72.5)

In [ ]:
b.prod()

np.float64(327364537.5)

`np.argmax()`   `np.argmin()`

In [ ]:
b.argmax()

np.int64(9)

In [ ]:
b.argmin()

np.int64(0)

`np.min()`   `np.max()`

In [ ]:
b.min()

np.float64(5.0)

In [ ]:
b.max()

np.float64(9.5)

`np.mean()`   `np.std()`

In [ ]:
b.mean()

np.float64(7.25)

In [ ]:
b.std()

np.float64(1.4361406616345072)

### Mathematical functions

`np.sin()`   `np.cos()`   `np.tan()`

In [ ]:
np.sin(1.047)

np.float64(0.8659266112878228)

In [ ]:
np.cos(1.047)

np.float64(0.5001710745970701)

In [ ]:
np.tan(1.047)

np.float64(1.7312608730630805)

`np.exp()`   `np.log()`   `np.log10()`

In [ ]:
np.exp(5.13)

np.float64(169.01711804488718)

In [ ]:
np.log(5.13)

np.float64(1.6351056591826783)

In [ ]:
np.log10(5.13)

np.float64(0.7101173651118162)

### Mathematical constants

`np.pi`   `np.e`

In [ ]:
np.pi

3.141592653589793

In [ ]:
np.e

2.718281828459045